# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: AHR University
email: abubakaryagob@gmail.com
name: AHR University
description: Education Start up
baseurl: 
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: blacksuan19
github_username:  blacksuan19

authors:
  blacksuan19:
    name: abubakar yagoub
    display_name: Abubakar Yagoub
    gravatar: e56154546cf4be74e393c62d1ae9f9d4
    email: Abubakaryagob@gmail.com
    web: https://github.com/blacksuan19
    twitter: https://twitter.com/blacksuan19
    description: "some nibba who codes in bash , works on the linux kernel and hates web development for some reason"
  hannan:
    name: hannan
    display_name: hannan
    gravatar: b1cc14991db7a456fcd761680bbc8f81
    email: wowthemesnet@gmail.com
    web: https://www.wowthemes.net/category/jekyll-themes/
    twitter: https://twitter.com/wowthemesnet
    description: "This is the author box. Write a short description of the author here. You are currently previewing Affiliates theme demo, a Jekyll template compatible with Github pages."
    rawdah:
    name: rawdah
    display_name: rawdah
    gravatar: b1cc14991db7a456fcd761680bbc8f81
    email: wowthemesnet@gmail.com
    web: https://www.wowthemes.net/category/jekyll-themes/
    twitter: https://twitter.com/wowthemesnet
    description: "This is the author box. Write a short description of the author here. You are currently previewing Affiliates theme demo, a Jekyll template compatible with Github pages."

# Build settings
plugins: 
  - jekyll-paginate
  - jekyll-archives

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Other
markdown: kramdown
highlighter: rouge
